# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        cd helper

        # Build
        go build -v -o helper_linux ./...
        GOOS=darwin go build -v -o helper_mac ./...
        GOOS=windows go build -v -o helper_win.exe ./...

        # Compress
        tar cf helper_linux.tar.gz helper_linux
        tar cf helper_mac.tar.gz helper_mac
        zip helper_win.zip helper_win.exe


    # - name: Archive Release for Linux
    #   uses: thedoctor0/zip-release@0.7.1
    #   with:
    #     type: 'tar'
    #     directory: 'helper'
    #     path: 'helper_linux'
    #     filename: 'helper_linux.tar.gz'
    # - name: Archive Release for Win
    #   uses: thedoctor0/zip-release@0.7.1
    #   with:
    #     type: 'zip'
    #     directory: 'helper'
    #     path: 'helper_win.exe'
    #     filename: 'helper_win.zip'
    # - name: Archive Release for Mac
    #   uses: thedoctor0/zip-release@0.7.1
    #   with:
    #     type: 'tar'
    #     directory: 'helper'
    #     path: 'helper_mac'
    #     filename: 'helper_mac.tar.gz'

    - name: Bump version and push tag
      if: ${{ github.ref == 'refs/heads/main' }}
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1.12.0
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        artifacts: "helper/helper_linux.tar.gz,helper/helper_win.zip,helper/helper_mac.tar.gz"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}